global:
  scrape_interval: 15s
  evaluation_interval: 15s

# rule_files:
#   - "alerts.yml"

# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#             - alertmanager:9093

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  
  - job_name: "auth-service"
    static_configs:
      - targets: ["auth-service:3006"]
    metrics_path: "/metrics"

  - job_name: "video-processing-service"
    static_configs:
      - targets: ["video-processing-service:3002"]
    metrics_path: "/metrics"



  - job_name: "notification-service"
    static_configs:
      - targets: ["notification-service:3004"]
    metrics_path: "/metrics"


