#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔍 Running pre-commit checks..."

# Run lint-staged
npx lint-staged

# Run quality checks
echo "🧪 Running tests..."
npm run test

echo "✅ Pre-commit checks passed!"
